
services:
  notely:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notely-app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=${DATABASE_URL:-}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - notely-network

networks:
  notely-network:
    driver: bridge