name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.0

      - name: Check GCP Secrets Setup
        run: |
          echo "Checking if GCP secrets are configured..."
          if [ -z "${{ secrets.GCP_SA_KEY }}" ]; then
            echo "❌ GCP_SA_KEY secret is not set"
            exit 1
          else
            echo "✅ GCP_SA_KEY secret is configured"
          fi
          
          if [ -z "${{ secrets.GCP_PROJECT_ID }}" ]; then
            echo "❌ GCP_PROJECT_ID secret is not set"
            exit 1
          else
            echo "✅ GCP_PROJECT_ID secret is configured"
            echo "Project ID: ${{ secrets.GCP_PROJECT_ID }}"
          fi

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Verify GCP Authentication
        run: |
          echo "Testing GCP authentication..."
          echo "Project ID: ${{ secrets.GCP_PROJECT_ID }}"
          echo "Checking if gcloud is authenticated..."
          gcloud auth list
          echo "Getting current project info..."
          gcloud config get-value project
          echo "Testing access to GCP services..."
          gcloud projects describe ${{ secrets.GCP_PROJECT_ID }}

    #   - name: Install dependencies
    #     run: go mod download

      - name: Build
        run: scripts/buildprod.sh 
